import "server-only";
import { generateObject } from "ai";
import { z } from "zod";
import { asc, eq } from "drizzle-orm";
import { db } from "@/lib/db";
import {
  bookings,
  clients,
  travelerPreferences,
  trips,
} from "@/lib/db/schema";
import { resolveAgent } from "@/lib/ai/registry";
import type { TripNarrative } from "@/lib/types/narrative";
import { findDestinationHero } from "@/lib/data/unsplash";

/**
 * Trip Narrative Agent
 *
 * Generates the editorial content shown on the public share page:
 * sensory hero opening, day themes, pre-trip notes, warm closing.
 * Persisted to trips.clientNarrative; regenerated by the operator.
 *
 * Re-uses agent_configs(client_briefing) — both are structured-copy
 * generators using the same Gemini model.
 */

const DaySchema = z.object({
  theme: z
    .string()
    .describe(
      "2–4 word evocative title for the day (e.g. 'Arrival, slow', 'Shrine mornings'). Title-cased.",
    ),
  blurb: z
    .string()
    .describe(
      "1–2 sentences of warm, second-person, sensory copy describing the feel of the day. No itemized lists, no facts the data doesn't support.",
    ),
  packingNote: z
    .string()
    .describe(
      "1 short sentence: what to bring or wear today specifically. Reference weather/activities when known. Concrete: 'Pack a light layer for the temple grounds — cool stone in the morning.' Not generic: 'Dress comfortably.'",
    ),
});

export const NarrativeSchema = z.object({
  heroEyebrow: z
    .string()
    .describe(
      "Short eyebrow above the trip title — 'Your trip', 'Your Japan', etc. 1–4 words.",
    ),
  heroOpening: z
    .string()
    .describe(
      "2–3 sentences. Second-person, sensory, anticipatory. Mention the destination by name and ground the feeling in one specific detail from the trip data (a hotel, a planned activity, the season). No salutation, no client name.",
    ),
  daySummaries: z
    .array(
      z.object({
        date: z.string().describe("yyyy-mm-dd"),
        ...DaySchema.shape,
      }),
    )
    .describe(
      "One entry per travel day. Date strings must match the dates of the trip's events exactly.",
    ),
  preTripNotes: z
    .array(
      z.object({
        label: z
          .string()
          .describe("1–2 words: 'Pack', 'Weather', 'Currency', 'Documents'"),
        body: z.string().describe("1–2 sentence practical note"),
      }),
    )
    .min(3)
    .max(5),
  closing: z
    .string()
    .describe(
      "1–2 warm sentences inviting the client to ask anything via the chat below. Sign with em-dash; the operator's name is appended automatically.",
    ),
});

export type NarrativeOutput = z.infer<typeof NarrativeSchema>;

const SYSTEM_PROMPT = `You are a private travel concierge writing a one-page client-facing trip overview. The tone is warm, slightly literary, never salesy or generic. The opening should make the client feel anticipated for, not sold to.

Hard rules:
- Second-person voice ("you", "your"). Never use the client's name in the body copy.
- Cite at least one specific detail from the trip data in the hero opening (a hotel name, a date, a destination feature). Do not invent venues, prices, or schedules.
- Day summaries should hint at the rhythm/feeling, not enumerate plans (the day-by-day events are listed separately on the page).
- Pre-trip notes must be practical and grounded: packing for the actual climate, currency, document needs. No hallucinated "good to know" facts.
- The closing should make replying feel inviting, not transactional.`;

export class NarrativeAgentError extends Error {}

export async function generateTripNarrative(
  tripId: string,
): Promise<TripNarrative> {
  const trip = await db.query.trips.findFirst({
    where: eq(trips.id, tripId),
    with: {
      client: { with: { preferences: true } },
      bookings: {
        orderBy: [asc(bookings.occursOn), asc(bookings.createdAt)],
      },
    },
  });
  if (!trip) {
    throw new NarrativeAgentError(`Trip ${tripId} not found`);
  }
  if (!trip.startDate || !trip.endDate) {
    throw new NarrativeAgentError(
      `Trip ${tripId} needs startDate and endDate before generating narrative.`,
    );
  }

  const resolved = await resolveAgent("client_briefing");

  const { object } = await generateObject({
    model: resolved.model,
    schema: NarrativeSchema,
    system: SYSTEM_PROMPT,
    prompt: buildPrompt(trip),
    temperature: resolved.settings?.temperature ?? 0.7,
  });

  /* Convert the array form into the keyed map shape we persist. */
  const daySummaries: TripNarrative["daySummaries"] = {};
  for (const d of object.daySummaries) {
    daySummaries[d.date] = {
      theme: d.theme,
      blurb: d.blurb,
      packingNote: d.packingNote,
    };
  }

  /* Fetch destination hero image in parallel (no-op if no API key). */
  const hero = await findDestinationHero(trip.destination);

  const narrative: TripNarrative = {
    heroEyebrow: object.heroEyebrow,
    heroOpening: object.heroOpening,
    daySummaries,
    preTripNotes: object.preTripNotes,
    closing: object.closing,
    hero: hero ?? null,
  };

  await db
    .update(trips)
    .set({
      clientNarrative: narrative,
      clientNarrativeGeneratedAt: new Date(),
      updatedAt: new Date(),
    })
    .where(eq(trips.id, tripId));

  return narrative;
}

function buildPrompt(
  trip: typeof trips.$inferSelect & {
    client: typeof clients.$inferSelect & {
      preferences: typeof travelerPreferences.$inferSelect | null;
    };
    bookings: (typeof bookings.$inferSelect)[];
  },
) {
  const start = new Date(trip.startDate!);
  const end = new Date(trip.endDate!);
  const nights = Math.max(
    1,
    Math.round((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24)),
  );

  const days = new Set<string>();
  for (const b of trip.bookings) {
    if (b.occursOn) days.add(b.occursOn);
  }

  const bookingsBlock = trip.bookings
    .map((b) => {
      const meta = (b.metadata ?? {}) as Record<string, unknown>;
      const time = meta.time as string | undefined;
      const icon = meta.icon as string | undefined;
      return `- ${b.occursOn ?? "?"} ${time ?? ""} ${icon ?? ""} [${b.kind}] ${b.title}${b.detail ? ` — ${b.detail.replace(/\n/g, " ")}` : ""}`;
    })
    .join("\n");

  const prefs = trip.client.preferences;
  const prefsLine = prefs
    ? [
        prefs.flightClass && `flightClass: ${prefs.flightClass}`,
        prefs.hotelStyle && `hotelStyle: ${prefs.hotelStyle}`,
        prefs.diningStyle && `dining: ${prefs.diningStyle}`,
        prefs.pacePreference && `pace: ${prefs.pacePreference}`,
      ]
        .filter(Boolean)
        .join(" · ")
    : "—";

  return [
    `Trip: ${trip.name} — ${trip.destination}`,
    `Dates: ${trip.startDate} → ${trip.endDate} (${nights} nights)`,
    `Travelers: ${trip.travelerCount}`,
    `Traveler preferences: ${prefsLine}`,
    "",
    "Bookings (day-by-day source of truth):",
    bookingsBlock || "(none yet)",
    "",
    `Travel days that need a daySummary entry: ${[...days].sort().join(", ") || "(no specific days yet — use the trip range)"}`,
    "",
    "Generate the narrative as a structured object. Keep daySummaries.date strings exactly matching the dates above. preTripNotes should reflect the actual climate / currency / language at the destination, not generic travel advice.",
  ].join("\n");
}
