/* Editorial content rendered on the public share page (/share/trip/...).
 * Generated by the Trip Narrative agent and persisted to
 * trips.clientNarrative as JSON. Read-only on the share page. */

export type TripNarrative = {
  /** Small uppercase eyebrow above the trip title. */
  heroEyebrow: string;
  /** 2–3 sentence sensory opening, second-person, anticipatory. */
  heroOpening: string;
  /** Map of yyyy-mm-dd → { theme, blurb } for each travel day. */
  daySummaries: Record<string, { theme: string; blurb: string }>;
  /** Practical pre-trip notes — packing, weather, docs, currency. */
  preTripNotes: { label: string; body: string }[];
  /** Warm 1–2 sentence sign-off shown above the chat. */
  closing: string;
};
