/* Editorial content rendered on the public share page (/share/trip/...).
 * Generated by the Trip Narrative agent and persisted to
 * trips.clientNarrative as JSON. Read-only on the share page. */

export type TripDaySummary = {
  theme: string;
  blurb: string;
  /** Single sentence: what to bring / wear today, weather-aware. */
  packingNote?: string;
};

export type TripHero = {
  imageUrl: string;
  thumbUrl: string;
  authorName: string;
  authorUrl: string;
};

export type TripNarrative = {
  /** Small uppercase eyebrow above the trip title. */
  heroEyebrow: string;
  /** 2–3 sentence sensory opening, second-person, anticipatory. */
  heroOpening: string;
  /** Map of yyyy-mm-dd → { theme, blurb, packingNote } for each day. */
  daySummaries: Record<string, TripDaySummary>;
  /** Practical pre-trip notes — packing, weather, docs, currency. */
  preTripNotes: { label: string; body: string }[];
  /** Warm 1–2 sentence sign-off shown above the chat. */
  closing: string;
  /** Unsplash hero image (when UNSPLASH_ACCESS_KEY available). */
  hero?: TripHero | null;
};
